#define WINDOW_WIDTH    640
#define WINDOW_HEIGHT   960

#define KINECT_WIDTH    XN_VGA_X_RES
#define KINECT_HEIGHT   XN_VGA_Y_RES

#define WORLD_WIDTH    6.4
#define WORLD_HEIGHT   9.6
#define WORLD_BOTTOM   1.0
