#define WINDOW_WIDTH    1000
#define WINDOW_HEIGHT   900

#define KINECT_WIDTH    XN_VGA_X_RES
#define KINECT_HEIGHT   XN_VGA_Y_RES

#define WORLD_WIDTH    6.4
#define WORLD_HEIGHT   9.6
#define WORLD_BOTTOM   0.0
